// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClGJJptFjsjUxfK17XsX102inUURBbYp4',
    appId: '1:548972387191:web:c6c499aec9caf48fc81f72',
    messagingSenderId: '548972387191',
    projectId: 'navigation-app-7234c',
    authDomain: 'navigation-app-7234c.firebaseapp.com',
    storageBucket: 'navigation-app-7234c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC1uqTXTFR8qQ1qCDi8z8sND9a9-2ejJk',
    appId: '1:548972387191:android:9db5f36635a98047c81f72',
    messagingSenderId: '548972387191',
    projectId: 'navigation-app-7234c',
    storageBucket: 'navigation-app-7234c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4SNNMRcSAHfWWTdqriswhVm6w8dnIapE',
    appId: '1:548972387191:ios:2bf881c28b0a5a7ac81f72',
    messagingSenderId: '548972387191',
    projectId: 'navigation-app-7234c',
    storageBucket: 'navigation-app-7234c.appspot.com',
    iosBundleId: 'com.example.arNavigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4SNNMRcSAHfWWTdqriswhVm6w8dnIapE',
    appId: '1:548972387191:ios:2bf881c28b0a5a7ac81f72',
    messagingSenderId: '548972387191',
    projectId: 'navigation-app-7234c',
    storageBucket: 'navigation-app-7234c.appspot.com',
    iosBundleId: 'com.example.arNavigation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClGJJptFjsjUxfK17XsX102inUURBbYp4',
    appId: '1:548972387191:web:f672fc873b9aaf7ec81f72',
    messagingSenderId: '548972387191',
    projectId: 'navigation-app-7234c',
    authDomain: 'navigation-app-7234c.firebaseapp.com',
    storageBucket: 'navigation-app-7234c.appspot.com',
  );
}
